//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyphonghoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class giangvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public giangvien()
        {
            this.phancongs = new HashSet<phancong>();
        }
    
        public string magv { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public string matrinhdo { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual trinhdo trinhdo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phancong> phancongs { get; set; }
    }
}
