//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyphonghoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string tenguoidung { get; set; }
        public Nullable<int> quyen { get; set; }
        public string motaquyen { get; set; }
    }
}
