//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyphonghoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkb
    {
        public string mapc { get; set; }
        public int buoihoc { get; set; }
        public string maphong { get; set; }
    
        public virtual buoihoc buoihoc1 { get; set; }
        public virtual phancong phancong { get; set; }
        public virtual phonghoc phonghoc { get; set; }
    }
}
