//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlyphonghoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class trinhdo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trinhdo()
        {
            this.giangviens = new HashSet<giangvien>();
        }
    
        public string matrinhdo { get; set; }
        public string trentrinhdo { get; set; }
        public double hesoluong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giangvien> giangviens { get; set; }
    }
}
